# encoding: UTF-8

require 'spec_helper'

describe "Exchange::ISO" do
  let(:subject) { Exchange::ISO }
  describe "self.definitions" do
    it "should be a hash of exactly the ISO standard definitions loaded from the yaml file" do
      subject.definitions.should === { 
               :aed => {:format=>"#,###.##", :minor_unit=>2, :currency=>"UAE Dirham", :symbol=>nil},
               :afn => {:minor_unit=>2, :currency=>"Afghani", :symbol=>"؋"},
               :all => {:minor_unit=>2, :currency=>"Lek", :symbol=>"Lek"},
               :amd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Armenian Dram", :symbol=>nil},
               :ang => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Netherlands Antillean Guilder", :symbol=>"ƒ"},
               :aoa => {:minor_unit=>2, :currency=>"Kwanza", :symbol=>nil},
               :ars => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Argentine Peso", :symbol=>"$"},
               :aud => {:format=>"# ###.##", :minor_unit=>2, :currency=>"Australian Dollar", :symbol=>"$"},
               :awg => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Aruban Florin", :symbol=>"ƒ"},
               :azn => {:minor_unit=>2, :currency=>"Azerbaijanian Manat", :symbol=>"ман"},
               :bam => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Convertible Mark", :symbol=>"KM"},
               :bbd => {:minor_unit=>2, :currency=>"Barbados Dollar", :symbol=>"$"},
               :bdt => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Taka", :symbol=>nil},
               :bgn => {:minor_unit=>2, :currency=>"Bulgarian Lev", :symbol=>"лв"},
               :bhd => {:format=>"#,###.###", :minor_unit=>3, :currency=>"Bahraini Dinar", :symbol=>nil},
               :bif => {:minor_unit=>0, :currency=>"Burundi Franc", :symbol=>nil},
               :bmd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Bermudian Dollar", :symbol=>"$"},
               :bnd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Brunei Dollar", :symbol=>"$"},
               :bob => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Boliviano", :symbol=>"$b"},
               :bov => {:minor_unit=>2, :currency=>"Mvdol", :symbol=>nil},
               :brl => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Brazilian Real", :symbol=>"R$"},
               :bsd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Bahamian Dollar", :symbol=>"$"},
               :btn => {:minor_unit=>2, :currency=>"Ngultrum", :symbol=>nil},
               :bwp => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Pula", :symbol=>"P"},
               :byr => {:minor_unit=>0, :currency=>"Belarussian Ruble", :symbol=>"p."},
               :bzd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Belize Dollar", :symbol=>"BZ$"},
               :cad => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Canadian Dollar", :symbol=>"$"},
               :cdf => {:minor_unit=>2, :currency=>"Congolese Franc", :symbol=>nil},
               :chf => {:format=>"#'###.##", :minor_unit=>2, :currency=>"Swiss Franc", :symbol=>"CHF"},
               :chw => {:minor_unit=>2, :currency=>"WIR Franc", :symbol=>nil},
               :clf => {:minor_unit=>0, :currency=>"Unidades de fomento", :symbol=>nil},
               :clp => {:format=>"#.###", :minor_unit=>0, :currency=>"Chilean Peso", :symbol=>"$"},
               :cny => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Yuan Renminbi", :symbol=>"¥"},
               :cop => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Colombian Peso", :symbol=>"$"},
               :cou => {:minor_unit=>2, :currency=>"Unidad de Valor Real", :symbol=>nil},
               :crc => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Costa Rican Colon", :symbol=>"₡"},
               :cuc => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Peso Convertible", :symbol=>nil},
               :cup => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Cuban Peso", :symbol=>"₱"},
               :cve => {:minor_unit=>2, :currency=>"Cape Verde Escudo", :symbol=>nil},
               :czk => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Czech Koruna", :symbol=>"Kč"},
               :djf => {:minor_unit=>0, :currency=>"Djibouti Franc", :symbol=>nil},
               :dkk => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Danish Krone", :symbol=>"kr"},
               :dop => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Dominican Peso", :symbol=>"RD$"},
               :dzd => {:minor_unit=>2, :currency=>"Algerian Dinar", :symbol=>nil},
               :egp => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Egyptian Pound", :symbol=>"£"},
               :ern => {:minor_unit=>2, :currency=>"Nakfa", :symbol=>nil},
               :etb => {:minor_unit=>2, :currency=>"Ethiopian Birr", :symbol=>nil},
               :eur => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Euro", :symbol=>"€"},
               :fjd => {:minor_unit=>2, :currency=>"Fiji Dollar", :symbol=>"$"},
               :fkp => {:minor_unit=>2, :currency=>"Falkland Islands Pound", :symbol=>"£"},
               :gbp => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Pound Sterling", :symbol=>"£"},
               :gel => {:minor_unit=>2, :currency=>"Lari", :symbol=>nil},
               :ghs => {:minor_unit=>2, :currency=>"Ghana Cedi", :symbol=>nil},
               :gip => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Gibraltar Pound", :symbol=>"£"},
               :gmd => {:minor_unit=>2, :currency=>"Dalasi", :symbol=>nil},
               :gnf => {:minor_unit=>0, :currency=>"Guinea Franc", :symbol=>nil},
               :gtq => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Quetzal", :symbol=>"Q"},
               :gyd => {:minor_unit=>2, :currency=>"Guyana Dollar", :symbol=>"$"},
               :hkd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Hong Kong Dollar", :symbol=>"$"},
               :hnl => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Lempira", :symbol=>"L"},
               :hrk => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Croatian Kuna", :symbol=>"kn"},
               :htg => {:minor_unit=>2, :currency=>"Gourde", :symbol=>nil},
               :huf => {:format=>"#.###", :minor_unit=>2, :currency=>"Forint", :symbol=>"Ft"},
               :idr => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Rupiah", :symbol=>"Rp"},
               :ils => {:format=>"#,###.##", :minor_unit=>2, :currency=>"New Israeli Sheqel", :symbol=>"₪"},
               :inr => {:format=>"#,##,###.##", :minor_unit=>2, :currency=>"Indian Rupee", :symbol=>""},
               :iqd => {:minor_unit=>3, :currency=>"Iraqi Dinar", :symbol=>nil},
               :irr => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Iranian Rial", :symbol=>"﷼"},
               :isk => {:format=>"#.###", :minor_unit=>0, :currency=>"Iceland Krona", :symbol=>"kr"},
               :jmd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Jamaican Dollar", :symbol=>"J$"},
               :jod => {:format=>"#,###.###", :minor_unit=>3, :currency=>"Jordanian Dinar", :symbol=>nil},
               :jpy => {:format=>"#,###", :minor_unit=>0, :currency=>"Yen", :symbol=>"¥"},
               :kes => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Kenyan Shilling", :symbol=>nil},
               :kgs => {:minor_unit=>2, :currency=>"Som", :symbol=>"лв"},
               :khr => {:minor_unit=>2, :currency=>"Riel", :symbol=>"៛"},
               :kmf => {:minor_unit=>0, :currency=>"Comoro Franc", :symbol=>nil},
               :kpw => {:minor_unit=>2, :currency=>"North Korean Won", :symbol=>"₩"},
               :krw => {:format=>"#,###", :minor_unit=>0, :currency=>"Won", :symbol=>"₩"},
               :kwd => {:format=>"#,###.###", :minor_unit=>3, :currency=>"Kuwaiti Dinar", :symbol=>nil},
               :kyd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Cayman Islands Dollar", :symbol=>"$"},
               :kzt => {:minor_unit=>2, :currency=>"Tenge", :symbol=>"лв"},
               :lak => {:minor_unit=>2, :currency=>"Kip", :symbol=>"₭"},
               :lbp => {:format=>"# ###", :minor_unit=>2, :currency=>"Lebanese Pound", :symbol=>"£"},
               :lkr => {:minor_unit=>2, :currency=>"Sri Lanka Rupee", :symbol=>"₨"},
               :lrd => {:minor_unit=>2, :currency=>"Liberian Dollar", :symbol=>"$"},
               :lsl => {:minor_unit=>2, :currency=>"Loti", :symbol=>nil},
               :ltl => {:format=>"# ###,##", :minor_unit=>2, :currency=>"Lithuanian Litas", :symbol=>"Lt"},
               :lvl => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Latvian Lats", :symbol=>"Ls"},
               :lyd => {:minor_unit=>3, :currency=>"Libyan Dinar", :symbol=>nil},
               :mad => {:minor_unit=>2, :currency=>"Moroccan Dirham", :symbol=>nil},
               :mdl => {:minor_unit=>2, :currency=>"Moldovan Leu", :symbol=>nil},
               :mga => {:minor_unit=>2, :currency=>"Malagasy Ariary", :symbol=>nil},
               :mkd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Denar", :symbol=>"ден"},
               :mmk => {:minor_unit=>2, :currency=>"Kyat", :symbol=>nil},
               :mnt => {:minor_unit=>2, :currency=>"Tugrik", :symbol=>"₮"},
               :mop => {:minor_unit=>2, :currency=>"Pataca", :symbol=>nil},
               :mro => {:minor_unit=>2, :currency=>"Ouguiya", :symbol=>nil},
               :mur => {:format=>"#,###", :minor_unit=>2, :currency=>"Mauritius Rupee", :symbol=>"₨"},
               :mvr => {:minor_unit=>2, :currency=>"Rufiyaa", :symbol=>nil},
               :mwk => {:minor_unit=>2, :currency=>"Kwacha", :symbol=>nil},
               :mxn => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Mexican Peso", :symbol=>"$"},
               :mxv => {:minor_unit=>2, :currency=>"Mexican Unidad de Inversion (UDI)", :symbol=>nil},
               :myr => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Malaysian Ringgit", :symbol=>"RM"},
               :mzn => {:minor_unit=>2, :currency=>"Mozambique Metical", :symbol=>"MT"},
               :nad => {:minor_unit=>2, :currency=>"Namibia Dollar", :symbol=>"$"},
               :ngn => {:minor_unit=>2, :currency=>"Naira", :symbol=>"₦"},
               :nio => {:minor_unit=>2, :currency=>"Cordoba Oro", :symbol=>"C$"},
               :nok => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Norwegian Krone", :symbol=>"kr"},
               :npr => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Nepalese Rupee", :symbol=>"₨"},
               :nzd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"New Zealand Dollar", :symbol=>"$"},
               :omr => {:format=>"#,###.###", :minor_unit=>3, :currency=>"Rial Omani", :symbol=>"﷼"},
               :pab => {:minor_unit=>2, :currency=>"Balboa", :symbol=>"B/."},
               :pen => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Nuevo Sol", :symbol=>"S/."},
               :pgk => {:minor_unit=>2, :currency=>"Kina", :symbol=>nil},
               :php => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Philippine Peso", :symbol=>"₱"},
               :pkr => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Pakistan Rupee", :symbol=>"₨"},
               :pln => {:format=>"# ###,##", :minor_unit=>2, :currency=>"Zloty", :symbol=>"zł"},
               :pyg => {:minor_unit=>0, :currency=>"Guarani", :symbol=>"Gs"},
               :qar => {:minor_unit=>2, :currency=>"Qatari Rial", :symbol=>"﷼"},
               :ron => {:format=>"#.###,##", :minor_unit=>2, :currency=>"New Romanian Leu", :symbol=>"lei"},
               :rsd => {:minor_unit=>2, :currency=>"Serbian Dinar", :symbol=>"Дин."},
               :rub => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Russian Ruble", :symbol=>"руб"},
               :rwf => {:minor_unit=>0, :currency=>"Rwanda Franc", :symbol=>nil},
               :sar => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Saudi Riyal", :symbol=>"﷼"},
               :sbd => {:minor_unit=>2, :currency=>"Solomon Islands Dollar", :symbol=>"$"},
               :scr => {:minor_unit=>2, :currency=>"Seychelles Rupee", :symbol=>"₨"},
               :sdg => {:minor_unit=>2, :currency=>"Sudanese Pound", :symbol=>nil},
               :sek => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Swedish Krona", :symbol=>"kr"},
               :sgd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Singapore Dollar", :symbol=>"$"},
               :shp => {:minor_unit=>2, :currency=>"Saint Helena Pound", :symbol=>"£"},
               :sll => {:minor_unit=>2, :currency=>"Leone", :symbol=>nil},
               :sos => {:minor_unit=>2, :currency=>"Somali Shilling", :symbol=>"S"},
               :srd => {:minor_unit=>2, :currency=>"Surinam Dollar", :symbol=>"$"},
               :ssp => {:minor_unit=>2, :currency=>"South Sudanese Pound", :symbol=>nil},
               :std => {:minor_unit=>2, :currency=>"Dobra", :symbol=>nil},
               :svc => {:format=>"#,###.##", :minor_unit=>2, :currency=>"El Salvador Colon", :symbol=>"$"},
               :syp => {:minor_unit=>2, :currency=>"Syrian Pound", :symbol=>"£"},
               :szl => {:format=>"#, ###.##", :minor_unit=>2, :currency=>"Lilangeni", :symbol=>nil},
               :thb => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Baht", :symbol=>"฿"},
               :tjs => {:minor_unit=>2, :currency=>"Somoni", :symbol=>nil},
               :tmt => {:minor_unit=>2, :currency=>"Turkmenistan New Manat", :symbol=>nil},
               :tnd => {:minor_unit=>3, :currency=>"Tunisian Dinar", :symbol=>nil},
               :top => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Pa\xE2\x80\x99anga", :symbol=>nil},
               :try => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Turkish Lira", :symbol=>""},
               :ttd => {:minor_unit=>2, :currency=>"Trinidad and Tobago Dollar", :symbol=>"TT$"},
               :twd => {:minor_unit=>2, :currency=>"New Taiwan Dollar", :symbol=>"NT$"},
               :tzs => {:format=>"#,###.##", :minor_unit=>2, :currency=>"Tanzanian Shilling", :symbol=>nil},
               :uah => {:format=>"# ###,##", :minor_unit=>2, :currency=>"Hryvnia", :symbol=>"₴"},
               :ugx => {:minor_unit=>2, :currency=>"Uganda Shilling", :symbol=>nil},
               :usd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"US Dollar", :symbol=>"$"},
               :usn => {:minor_unit=>2, :currency=>"US Dollar (Next day)", :symbol=>nil},
               :uss => {:minor_unit=>2, :currency=>"US Dollar (Same day)", :symbol=>nil},
               :uyi => {:minor_unit=>0, :currency=>"Uruguay Peso en Unidades Indexadas (URUIURUI)", :symbol=>nil},
               :uyu => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Peso Uruguayo", :symbol=>"$U"},
               :uzs => {:minor_unit=>2, :currency=>"Uzbekistan Sum", :symbol=>"лв"},
               :vef => {:format=>"#.###,##", :minor_unit=>2, :currency=>"Bolivar Fuerte", :symbol=>"Bs"},
               :vnd => {:format=>"#.###", :minor_unit=>0, :currency=>"Dong", :symbol=>"₫"},
               :vuv => {:format=>"#,###", :minor_unit=>0, :currency=>"Vatu", :symbol=>nil},
               :wst => {:minor_unit=>2, :currency=>"Tala", :symbol=>nil},
               :xaf => {:minor_unit=>0, :currency=>"CFA Franc BEAC", :symbol=>nil},
               :xcd => {:format=>"#,###.##", :minor_unit=>2, :currency=>"East Caribbean Dollar", :symbol=>"$"},
               :xof => {:minor_unit=>0, :currency=>"CFA Franc BCEAO", :symbol=>nil},
               :xpf => {:minor_unit=>0, :currency=>"CFP Franc", :symbol=>nil},
               :yer => {:minor_unit=>2, :currency=>"Yemeni Rial", :symbol=>"﷼"},
               :zar => {:format=>"# ###.##", :minor_unit=>2, :currency=>"Rand", :symbol=>"R"},
               :zmk => {:minor_unit=>2, :currency=>"Zambian Kwacha", :symbol=>nil},
               :zwl => {:minor_unit=>2, :currency=>"Zimbabwe Dollar", :symbol=>nil}
                                      }
    end
  end
  describe "self.country_map" do
    it "should deliver a complete map of country abbreviations to currencies" do
      subject.country_map.should == {
        :abw => :awg,
        :ad => :eur,
        :ae => :aed,
        :af => :afn,
        :afg => :afn,
        :ag => :xcd,
        :ago => :aoa,
        :ai => :xcd,
        :aia => :xcd,
        :al => :all,
        :ala => :eur,
        :alb => :all,
        :am => :amd,
        :and => :eur,
        :ao => :aoa,
        :ar => :ars,
        :are => :aed,
        :arg => :ars,
        :arm => :amd,
        :as => :usd,
        :asm => :usd,
        :at => :eur,
        :atf => :eur,
        :atg => :xcd,
        :au => :aud,
        :aus => :aud,
        :aut => :eur,
        :aw => :awg,
        :ax => :eur,
        :az => :azn,
        :aze => :azn,
        :ba => :bam,
        :bb => :bbd,
        :bd => :bdt,
        :bdi => :bif,
        :be => :eur,
        :bel => :eur,
        :ben => :xof,
        :bes => :usd,
        :bf => :xof,
        :bfa => :xof,
        :bg => :bgn,
        :bgd => :bdt,
        :bgr => :bgn,
        :bh => :bhd,
        :bhr => :bhd,
        :bhs => :bsd,
        :bi => :bif,
        :bih => :bam,
        :bj => :xof,
        :bl => :eur,
        :blm => :eur,
        :blr => :byr,
        :blz => :bzd,
        :bm => :bmd,
        :bmu => :bmd,
        :bn => :bnd,
        :bo => :bov,
        :bol => :bov,
        :bq => :usd,
        :br => :brl,
        :bra => :brl,
        :brb => :bbd,
        :brn => :bnd,
        :bs => :bsd,
        :bt => :btn,
        :btn => :btn,
        :bv => :nok,
        :bvt => :nok,
        :bw => :bwp,
        :bwa => :bwp,
        :by => :byr,
        :bz => :bzd,
        :ca => :cad,
        :caf => :xaf,
        :can => :cad,
        :cc => :aud,
        :cck => :aud,
        :cd => :cdf,
        :cf => :xaf,
        :cg => :xaf,
        :ch => :chf,
        :che => :chf,
        :chl => :clf,
        :chn => :cny,
        :ci => :xof,
        :civ => :xof,
        :ck => :nzd,
        :cl => :clf,
        :cm => :xaf,
        :cmr => :xaf,
        :cn => :cny,
        :co => :cou,
        :cod => :cdf,
        :cog => :xaf,
        :cok => :nzd,
        :col => :cou,
        :com => :kmf,
        :cpv => :cve,
        :cr => :crc,
        :cri => :crc,
        :cu => :cuc,
        :cub => :cuc,
        :cuw => :ang,
        :cv => :cve,
        :cw => :ang,
        :cx => :aud,
        :cxr => :aud,
        :cy => :eur,
        :cym => :kyd,
        :cyp => :eur,
        :cz => :czk,
        :cze => :czk,
        :de => :eur,
        :deu => :eur,
        :dj => :djf,
        :dji => :djf,
        :dk => :dkk,
        :dm => :xcd,
        :dma => :xcd,
        :dnk => :dkk,
        :do => :dop,
        :dom => :dop,
        :dz => :dzd,
        :dza => :dzd,
        :ec => :usd,
        :ecu => :usd,
        :ee => :eur,
        :eg => :egp,
        :egy => :egp,
        :eh => :mad,
        :er => :ern,
        :eri => :ern,
        :es => :eur,
        :esh => :mad,
        :esp => :eur,
        :est => :eur,
        :et => :etb,
        :eth => :etb,
        :fi => :eur,
        :fin => :eur,
        :fj => :fjd,
        :fji => :fjd,
        :fk => :fkp,
        :flk => :fkp,
        :fm => :usd,
        :fo => :dkk,
        :fr => :eur,
        :fra => :eur,
        :fro => :dkk,
        :fsm => :usd,
        :ga => :xaf,
        :gab => :xaf,
        :gb => :gbp,
        :gbr => :gbp,
        :gd => :xcd,
        :ge => :gel,
        :geo => :gel,
        :gf => :eur,
        :gg => :gbp,
        :ggy => :gbp,
        :gh => :ghs,
        :gha => :ghs,
        :gi => :gip,
        :gib => :gip,
        :gin => :gnf,
        :gl => :dkk,
        :glp => :eur,
        :gm => :gmd,
        :gmb => :gmd,
        :gn => :gnf,
        :gnb => :xof,
        :gnq => :xaf,
        :gp => :eur,
        :gq => :xaf,
        :gr => :eur,
        :grc => :eur,
        :grd => :xcd,
        :grl => :dkk,
        :gt => :gtq,
        :gtm => :gtq,
        :gu => :usd,
        :guf => :eur,
        :gum => :usd,
        :guy => :gyd,
        :gw => :xof,
        :gy => :gyd,
        :hk => :hkd,
        :hkg => :hkd,
        :hm => :aud,
        :hmd => :aud,
        :hn => :hnl,
        :hnd => :hnl,
        :hr => :hrk,
        :hrv => :hrk,
        :ht => :usd,
        :hti => :usd,
        :hu => :huf,
        :hun => :huf,
        :id => :idr,
        :idn => :idr,
        :ie => :eur,
        :il => :ils,
        :im => :gbp,
        :imn => :gbp,
        :in => :inr,
        :ind => :inr,
        :io => :usd,
        :iot => :usd,
        :iq => :iqd,
        :ir => :irr,
        :irl => :eur,
        :irn => :irr,
        :irq => :iqd,
        :is => :isk,
        :isl => :isk,
        :isr => :ils,
        :it => :eur,
        :ita => :eur,
        :jam => :jmd,
        :je => :gbp,
        :jey => :gbp,
        :jm => :jmd,
        :jo => :jod,
        :jor => :jod,
        :jp => :jpy,
        :jpn => :jpy,
        :kaz => :kzt,
        :ke => :kes,
        :ken => :kes,
        :kg => :kgs,
        :kgz => :kgs,
        :kh => :khr,
        :khm => :khr,
        :ki => :aud,
        :kir => :aud,
        :km => :kmf,
        :kn => :xcd,
        :kna => :xcd,
        :kor => :krw,
        :kp => :kpw,
        :kr => :krw,
        :kw => :kwd,
        :kwt => :kwd,
        :ky => :kyd,
        :kz => :kzt,
        :la => :lak,
        :lao => :lak,
        :lb => :lbp,
        :lbn => :lbp,
        :lbr => :lrd,
        :lby => :lyd,
        :lc => :xcd,
        :lca => :xcd,
        :li => :chf,
        :lie => :chf,
        :lk => :lkr,
        :lka => :lkr,
        :lr => :lrd,
        :ls => :zar,
        :lso => :zar,
        :lt => :ltl,
        :ltu => :ltl,
        :lu => :eur,
        :lux => :eur,
        :lv => :lvl,
        :lva => :lvl,
        :ly => :lyd,
        :ma => :mad,
        :mac => :mop,
        :maf => :eur,
        :mar => :mad,
        :mc => :eur,
        :mco => :eur,
        :md => :mdl,
        :mda => :mdl,
        :mdg => :mga,
        :mdv => :mvr,
        :me => :eur,
        :mex => :mxn,
        :mf => :eur,
        :mg => :mga,
        :mh => :usd,
        :mhl => :usd,
        :mk => :mkd,
        :mkd => :mkd,
        :ml => :xof,
        :mli => :xof,
        :mlt => :eur,
        :mm => :mmk,
        :mmr => :mmk,
        :mn => :mnt,
        :mne => :eur,
        :mng => :mnt,
        :mnp => :usd,
        :mo => :mop,
        :moz => :mzn,
        :mp => :usd,
        :mq => :eur,
        :mr => :mro,
        :mrt => :mro,
        :ms => :xcd,
        :msr => :xcd,
        :mt => :eur,
        :mtq => :eur,
        :mu => :mur,
        :mus => :mur,
        :mv => :mvr,
        :mw => :mwk,
        :mwi => :mwk,
        :mx => :mxn,
        :my => :myr,
        :mys => :myr,
        :myt => :eur,
        :mz => :mzn,
        :na => :zar,
        :nam => :zar,
        :nc => :xpf,
        :ncl => :xpf,
        :ne => :xof,
        :ner => :xof,
        :nf => :aud,
        :nfk => :aud,
        :ng => :ngn,
        :nga => :ngn,
        :ni => :nio,
        :nic => :nio,
        :niu => :nzd,
        :nl => :eur,
        :nld => :eur,
        :no => :nok,
        :nor => :nok,
        :np => :npr,
        :npl => :npr,
        :nr => :aud,
        :nru => :aud,
        :nu => :nzd,
        :nz => :nzd,
        :nzl => :nzd,
        :om => :omr,
        :omn => :omr,
        :pa => :usd,
        :pak => :pkr,
        :pan => :usd,
        :pcn => :nzd,
        :pe => :pen,
        :per => :pen,
        :pf => :xpf,
        :pg => :pgk,
        :ph => :php,
        :phl => :php,
        :pk => :pkr,
        :pl => :pln,
        :plw => :usd,
        :pm => :eur,
        :pn => :nzd,
        :png => :pgk,
        :pol => :pln,
        :pr => :usd,
        :pri => :usd,
        :prk => :kpw,
        :prt => :eur,
        :pry => :pyg,
        :pt => :eur,
        :pw => :usd,
        :py => :pyg,
        :pyf => :xpf,
        :qa => :qar,
        :qat => :qar,
        :re => :eur,
        :reu => :eur,
        :ro => :ron,
        :rou => :ron,
        :rs => :rsd,
        :ru => :rub,
        :rus => :rub,
        :rw => :rwf,
        :rwa => :rwf,
        :sa => :sar,
        :sau => :sar,
        :sb => :sbd,
        :sc => :scr,
        :sd => :sdg,
        :sdn => :sdg,
        :se => :sek,
        :sen => :xof,
        :sg => :sgd,
        :sgp => :sgd,
        :sh => :shp,
        :shn => :shp,
        :si => :eur,
        :sj => :nok,
        :sjm => :nok,
        :sk => :eur,
        :sl => :sll,
        :slb => :sbd,
        :sle => :sll,
        :slv => :usd,
        :sm => :eur,
        :smr => :eur,
        :sn => :xof,
        :so => :sos,
        :som => :sos,
        :spm => :eur,
        :sr => :srd,
        :srb => :rsd,
        :ss => :ssp,
        :ssd => :ssp,
        :st => :std,
        :stp => :std,
        :sur => :srd,
        :sv => :usd,
        :svk => :eur,
        :svn => :eur,
        :swe => :sek,
        :swz => :szl,
        :sx => :ang,
        :sxm => :ang,
        :sy => :syp,
        :syc => :scr,
        :syr => :syp,
        :sz => :szl,
        :tc => :usd,
        :tca => :usd,
        :tcd => :xaf,
        :td => :xaf,
        :tf => :eur,
        :tg => :xof,
        :tgo => :xof,
        :th => :thb,
        :tha => :thb,
        :tj => :tjs,
        :tjk => :tjs,
        :tk => :nzd,
        :tkl => :nzd,
        :tkm => :tmt,
        :tl => :usd,
        :tls => :usd,
        :tm => :tmt,
        :tn => :tnd,
        :to => :top,
        :ton => :top,
        :tr => :try,
        :tt => :ttd,
        :tto => :ttd,
        :tun => :tnd,
        :tur => :try,
        :tuv => :aud,
        :tv => :aud,
        :tw => :twd,
        :twn => :twd,
        :tz => :tzs,
        :tza => :tzs,
        :ua => :uah,
        :ug => :ugx,
        :uga => :ugx,
        :ukr => :uah,
        :um => :usd,
        :umi => :usd,
        :ury => :uyu,
        :us => :usd,
        :usa => :usd,
        :uy => :uyu,
        :uz => :uzs,
        :uzb => :uzs,
        :va => :eur,
        :vat => :eur,
        :vc => :xcd,
        :vct => :xcd,
        :ve => :vef,
        :ven => :vef,
        :vg => :usd,
        :vgb => :usd,
        :vi => :usd,
        :vir => :usd,
        :vn => :vnd,
        :vnm => :vnd,
        :vu => :vuv,
        :vut => :vuv,
        :wf => :xpf,
        :wlf => :xpf,
        :ws => :wst,
        :wsm => :wst,
        :ye => :yer,
        :yem => :yer,
        :yt => :eur,
        :za => :zar,
        :zaf => :zar,
        :zm => :zmk,
        :zmb => :zmk,
        :zw => :zwl,
        :zwe => :zwl
      }
    end
  end
  describe "self.currencies" do
    it "should be an array of currency symbols" do
      subject.currencies.should == %W(nio lak sar nok usd rub xcd omr amd cdf kpw cny kes khr pln mvr gtq clp inr bzd myr hkd cop dkk sek byr lyd ron dzd bif ars gip uyi bob ssp ngn pgk std xof aed ern mwk cup usn gmd cve tzs cou btn zwl ugx syp mad mnt lsl xaf shp htg rsd mga top mzn lvl fkp uss bwp hnl eur egp chf ils pyg lbp ang kzt gyd wst npr kmf thb irr srd jpy brl uyu mop bmd szl etb jod idr mdl xpf mro yer bam awg nzd pen aoa kyd sll try vef isk gnf bsd djf huf ltl mxn scr sgd lkr tjs tnd dop fjd gel sdg vuv bbd lrd krw mmk mur php zar kgs gbp bgn iqd tmt uah vnd zmk bov hrk ttd bhd clf rwf mkd aud crc pkr twd uzs czk azn bdt nad afn mxv cuc pab qar sos chw cad jmd bnd all svc sbd ghs kwd).sort.map(&:to_sym)
    end
  end
  describe "self.defines?" do
    context "with a defined currency" do
      it "should return true" do
        subject.currencies.each do |curr|
          subject.should be_defines(curr)
        end
      end
    end
    context "with a defined country" do
      it "should return true" do
        subject.country_map.each do |country, currency|
          subject.should be_defines(country)
        end
      end
    end
    context "with an undefined currency" do
      it "should return false" do
        subject.should_not be_defines(:xxx)
      end
    end
  end
  describe "self.assert_currency" do
    context "with a currency" do
      it "should return the currency itself" do
        subject.assert_currency!(:eur).should == :eur
      end
    end
    context "with a country" do
      it "should return the matching currency for the country" do
        subject.assert_currency!(:de).should == :eur
      end
    end
    context "with a non-currency" do
      it "should raise an error" do
        lambda { subject.assert_currency!(:xxx) }.should raise_error(Exchange::NoCurrencyError, "xxx is not a currency nor a country code matchable to a currency")
      end
    end
  end
  describe "self.instantiate" do
    context "given a float or an integer" do
      context "with bigger precision than the definition" do
        it "should instantiate a big decimal with the given precision" do
          BigDecimal.should_receive(:new).with('23.2345', 6).and_return('INSTANCE')
          subject.instantiate(23.2345, :tnd).should == 'INSTANCE'
          BigDecimal.should_receive(:new).with('22223.2323444', 12).and_return('INSTANCE')
          subject.instantiate(22223.2323444, :sar).should == 'INSTANCE'
          BigDecimal.should_receive(:new).with('23.23', 4).and_return('INSTANCE')
          subject.instantiate(23.23, :clp).should == 'INSTANCE'
        end
      end
      context "with smaller precision than the definition" do
        it "should instantiate a big decimal with the defined precision" do
          BigDecimal.should_receive(:new).with('23382343.1',11).and_return('INSTANCE')
          subject.instantiate(23382343.1, :tnd).should == 'INSTANCE'
          BigDecimal.should_receive(:new).with('23',4).and_return('INSTANCE')
          subject.instantiate(23, :sar).should == 'INSTANCE'
          BigDecimal.should_receive(:new).with('23.2',5).and_return('INSTANCE')
          subject.instantiate(23.2, :omr).should == 'INSTANCE'
        end
      end
    end
    context "given a big decimal" do
      let!(:bigdecimal) { BigDecimal.new("23.23") }
      it "should instantiate a big decimal according to the iso standards" do
        BigDecimal.should_receive(:new).never
        subject.instantiate(bigdecimal, :tnd).should == bigdecimal
      end
    end
  end
  describe "self.round" do
    it "should round a currency according to ISO 4217 Definitions" do
      subject.round(BigDecimal.new("23.232524"), :tnd).should == BigDecimal.new("23.233")
      subject.round(BigDecimal.new("23.232524"), :sar).should == BigDecimal.new("23.23")
      subject.round(BigDecimal.new("23.232524"), :clp).should == BigDecimal.new("23")
    end
  end
  describe "self.stringify" do
    it "should stringify a currency according to ISO 4217 Definitions" do
      subject.stringify(BigDecimal.new("23.232524"), :tnd).should == "TND 23.233"
      subject.stringify(BigDecimal.new("23.232524"), :sar).should == "SAR 23.23"
      subject.stringify(BigDecimal.new("23.232524"), :clp).should == "CLP 23"
      subject.stringify(BigDecimal.new("23.2"), :tnd).should == "TND 23.200"
      subject.stringify(BigDecimal.new("23.4"), :sar).should == "SAR 23.40"
      subject.stringify(BigDecimal.new("23.0"), :clp).should == "CLP 23"
    end
    context "amount only" do
      it "should not render the currency" do
        subject.stringify(BigDecimal.new("23.232524"), :tnd, :amount_only => true).should == "23.233"
        subject.stringify(BigDecimal.new("23.232524"), :sar, :amount_only => true).should == "23.23"
        subject.stringify(BigDecimal.new("23.232524"), :clp, :amount_only => true).should == "23"
        subject.stringify(BigDecimal.new("23.2"), :tnd, :amount_only => true).should == "23.200"
        subject.stringify(BigDecimal.new("23.4"), :sar, :amount_only => true).should == "23.40"
        subject.stringify(BigDecimal.new("23.0"), :clp, :amount_only => true).should == "23"
      end
    end
    context "symbol" do
      context "with a symbol present" do
        it "should render a symbol for the currency" do
          subject.stringify(BigDecimal.new("23.232524"), :usd, :symbol => true).should == "$23.23"
          subject.stringify(BigDecimal.new("23.232524"), :irr, :symbol => true).should == "﷼23.23"
          subject.stringify(BigDecimal.new("23.232524"), :gbp, :symbol => true).should == "£23.23"
          subject.stringify(BigDecimal.new("23.232524"), :eur, :symbol => true).should == "€23.23"
        end
      end
      context "without a symbol present" do
        it "should render the currency abbreviation" do
          subject.stringify(BigDecimal.new("23.232524"), :chf, :symbol => true).should == "CHF23.23"
          subject.stringify(BigDecimal.new("23.232524"), :etb, :symbol => true).should == "ETB23.23"
        end
      end
    end
  end
end