require 'exchange/external_api/configuration'
require 'exchange/external_api/base'
require 'exchange/external_api/xml'
require 'exchange/external_api/json'
require 'exchange/external_api/call'
require 'exchange/external_api/currency_bot'
require 'exchange/external_api/xavier_media'
require 'exchange/external_api/ecb'